services:
  onefm:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    environment:
      SITE_NAME: onefm.local
      DB_ROOT_PASSWORD: root
      ADMIN_PASSWORD: admin
    volumes:
      - ./apps:/home/frappe/frappe-bench/apps
    command: /home/frappe/entrypoint.sh